package infrastructure.dal.conection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Proxy on {@link Connection}. It is necessary to prevent the connection from being closed if the connection has
 * status autocommit=falls
 *
 * @author Vendelovskyi Ivan
 * @version 1.0
 */
public interface ConnectionProxy extends AutoCloseable {

    @Override
    void close() throws SQLException;

    void setAutoCommit(boolean isAutoCommit) throws SQLException;

    Connection getSubject();

    void rollBack() throws SQLException;

    void commit() throws SQLException;

    void setIsTransaction(boolean readyToClose);

    PreparedStatement prepareStatement(String sql) throws SQLException;

    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
}
